{% set name = "dbt-redshift" %}
{% set version = "1.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7f8bb7b1cb7ee029b8a457096a028df90c51a2b04ff01bfc82ad3da6055e3ca6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - requests
    - python >={{ python_min }}
    # via Grayskull
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.11,<2.0
    - dbt-postgres >=1.8,<1.10
    - redshift_connector <2.1.1,>=2.0.913,!=2.0.914
    - dbt-core >=1.8.0b3
    - sqlparse >=0.5.0,<0.6.0
    - agate

test:
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-redshift
  summary: The Redshift adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
