{% set name = "dbt-redshift" %}
{% set version = "1.9.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e75efff64dc8a79e3a2be665bbf8a1272d03cd0c9c1542f3d46bae7e53e2b363

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - requests
    - python >={{ python_min }}
    # via Grayskull
    - dbt-common >=1.10,<2.0
    - dbt-adapters >=1.11,<2.0
    - dbt-postgres >=1.8,<1.10
    - redshift_connector >=2.1.3,<2.2
    - dbt-core >=1.8.0b3
    - sqlparse >=0.5.0,<0.6.0
    - agate

test:
  imports:
    - dbt
    - dbt.adapters
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dbt-labs/dbt-redshift
  summary: The Redshift adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
    - maresb
    - thewchan
