{% set name = "dbt-redshift" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dbt_redshift-{{ version }}.tar.gz
  sha256: 3347e295944716abee4147314cfb6dac61001e48edd4e6d7f100dc0cbf4ec244

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - dbt-common >=0.1.0a1,<2.0
    - dbt-adapters >=0.1.0a1,<2.0
    - dbt-postgres >=1.8.0,<1.9.dev0
    - redshift_connector <2.0.918,>=2.0.913,!=2.0.914
    - dbt-core >=1.8.0b3
    - sqlparse >=0.5.0,<0.6.0
    - agate

test:
  imports:
    - dbt.adapters.redshift
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dbt-labs/dbt-redshift
  summary: The Redshift adapter plugin for dbt
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - maresb
    - thewchan
